name: LibraryTemplate
main: org.tal.librarytemplate.LibraryTemplate
version: 0.83
depend: [RedstoneChips]
commands:
  rc-test:
    description: Sends a test message to the player.
    usage:
      /<command>
